baseURL = "https://jcstr.dev"
title = "jcstr"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true



[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[params]
author = "Jesús Castro"
description = "Techie writings and thoughts"
keywords = "blog,developer,personal"
info = ["Software Engineer • Community Builder" "Passionate about Open Source"]
avatarURL = "https://i.imgur.com/gObdw6Q.jpg"
dateFormat = "2 January, 2006"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"

favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/jcstr/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/gccstr/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"
