baseURL = "https://jcstr.dev"
languageCode = "en-us"
title = "Jesús Castro"
theme = "etch"

enableEmoji = true
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Techie Writings and Thoughts"
  copyright = "© 2021 Jesús Castro · CC BY-NC 4.0"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
